packages/htmlbars-compiler/lib/fragment-javascript-compiler.js, packages/htmlbars-compiler/lib/fragment-opcode-compiler.js, packages/htmlbars-compiler/lib/hydration-javascript-compiler.js, packages/htmlbars-compiler/lib/hydration-opcode-compiler.js, packages/htmlbars-compiler/lib/utils.js, packages/htmlbars-compiler/tests/fragment-test.js, packages/htmlbars-compiler/tests/html-compiler-test.js, packages/htmlbars-compiler/tests/hydration-opcode-compiler-test.js, packages/morph/lib/attr-morph.js, packages/morph/lib/dom-helper.js, packages/morph/tests/attr-morph-test.js, packages/morph/tests/dom-helper-test.js
=> Implement #224 

.gitignore, .travis.yml, bin/run-tests.js, package.json, test/index.html, testem.json
Single tunnel per session
Updated faster tunnel
Extracted from: https://github.com/tildeio/htmlbars/pull/221
Fix #220
=> Improved sauce testing

packages/htmlbars-syntax/lib/tokenizer.js, packages/htmlbars-util/lib/array-utils.js
This causes a number of failures on IE8 in Ember.
=> Do not use Array.prototype.map.

Brocfile.js, bin/run-tests.js, package.json, test/index.html, testem.json
Extracted sauce into an addon / run browsers in parallel
=> Extracted sauce into an addon / run browsers in parallel

testem.json
This should make the default screenshots by saucelabs more helpful.
=> Hide passed tests by default.

packages/htmlbars-compiler/tests/fragment-test.js, packages/htmlbars-compiler/tests/html-compiler-test.js, packages/htmlbars-syntax/lib/utils.js, packages/htmlbars-test-helpers/lib/main.js, packages/htmlbars-util/lib/array-utils.js, packages/morph/lib/dom-helper.js, packages/morph/tests/attr-morph-test.js
First batch of changes ... feedback is greatly appreciated
=> IE8 compatibility

packages/htmlbars-compiler/tests/html-compiler-test.js, packages/htmlbars-compiler/tests/hydration-opcode-compiler-test.js, packages/htmlbars-syntax/lib/parser.js, packages/htmlbars-test-helpers/lib/main.js, packages/morph/tests/attr-morph-test.js, packages/morph/tests/dom-helper-test.js
A bit of clean-up, and getting all the failing/dying tests green.  Should be ready before too long, but it's never too early for feedback.  I am doing very short amend commits, though, so it might be a good idea to wait a bit until it's closer to being finalized... up to you.
=> Finish fixes for IE8

packages/htmlbars-compiler/tests/html-compiler-test.js
=> Add a note on disabled IE8 tests

.travis.yml, package.json
Before some async tests could finish after the result was published.
=> Improved test run finished detection

packages/morph-attr/lib/sanitize-attribute-value.js, packages/morph-attr/tests/attr-morph-test.js, packages/morph-attr/tests/attr-morph/sanitize-attribute-value-test.js
=> sanitize and test <embed src=data:… <base href

.travis.yml, package.json
Bundle start / stop commands
Thanks @rwjblue for the suggestion.
=> Updated sauce addon

demos/compile-and-run.html
Some recent changes broke compile-and-run, I think I fixed it! (see the commit messages for details about each change)
=> Fix compile and run

package.json, packages/htmlbars-compiler/lib/hydration-opcode-compiler.js, packages/htmlbars-syntax/lib/builders.js, packages/htmlbars-syntax/lib/node-handlers.js, packages/htmlbars-syntax/lib/token-handlers.js, packages/htmlbars-syntax/lib/tokenizer.js, packages/htmlbars-syntax/lib/utils.js, packages/htmlbars-syntax/tests/parser-node-test.js
=> Update handlebars AST

packages/htmlbars-runtime/lib/expression-visitor.js, packages/htmlbars-runtime/lib/hooks.js
This supports https://github.com/emberjs/ember.js/pull/11028
=> Adding params to component hook signature

packages/htmlbars-runtime/lib/main.js, packages/htmlbars-syntax/lib/builders.js, packages/htmlbars-syntax/lib/main.js, packages/htmlbars-syntax/lib/node-handlers.js, packages/htmlbars-syntax/lib/parser.js, packages/htmlbars-syntax/tests/loc-node-test.js, packages/htmlbars-syntax/tests/parser-node-test.js, packages/htmlbars/lib/main.js
I extracted some of the work from #342 and added tests.
I had to tweak imports because a cycle was causing an import to be undefined.
cc @rwjblue
=> Pass location info through for the Program node

packages/htmlbars-runtime/lib/render.js, packages/htmlbars-runtime/tests/main-test.js
sets namespace if `tagName` is SVG
=> manualElement handles SVG properly

.travis.yml, package.json, testem-sauce.json, testem.json
=> ember-cli-sauce v1.3.0

packages/htmlbars-runtime/lib/hooks.js, packages/htmlbars-runtime/tests/hooks-test.js, packages/htmlbars-runtime/tests/hooks.js
Thanks to @jmurphyau for the fix (in https://github.com/tildeio/htmlbars/pull/349)!
=> Allow falsey values from helpers.

packages/htmlbars-runtime/lib/expression-visitor.js
Tested successfully against Ember's test suite.
=> Visitor cleanup

packages/dom-helper/lib/prop.js, packages/dom-helper/tests/prop-test.js
Addresses:
* https://github.com/emberjs/ember.js/issues/10908
* https://github.com/emberjs/ember.js/issues/11364
=> Force <input> `list` to be set as an attribute.

packages/morph-attr/tests/attr-morph-test.js
=> Revert "extra tests for input.maxLength"

packages/htmlbars-compiler/tests/diffing-test.js, packages/htmlbars-runtime/lib/hooks.js, packages/htmlbars-util/lib/template-utils.js
=> handle duplicate keys

Brocfile.js, bench/index.html, package.json
To run the benchmark boot up ember serve and visit /bench/index.html. This is just the first step towards a more robust benchmark suite.
=> Add a basic benchmark harness

package.json
For: https://github.com/emberjs/ember.js/issues/12316
=> Update `morph-range` to v0.2.5

.jshintrc, packages/htmlbars-syntax/lib/parser/tokenizer-event-handlers.js, packages/htmlbars-syntax/tests/parser-node-test.js
=> Raise an error for script tags

packages/htmlbars-runtime/lib/hooks.js
Addresses https://github.com/tildeio/htmlbars/issues/420
=> quote 'yield' in lib/hooks

packages/htmlbars-syntax/lib/builders.js, packages/htmlbars-syntax/lib/parser/tokenizer-event-handlers.js, packages/htmlbars-syntax/tests/loc-node-test.js
@fivetanley + @rwjblue - Pairing === Love.
=> Add loc to text, comment, and attribute nodes.

packages/dom-helper/lib/main.js
=> Revert "Don't cast bools"

packages/htmlbars-compiler/lib/hydration-javascript-compiler.js, packages/htmlbars-compiler/tests/dirtying-test.js, packages/htmlbars-compiler/tests/hydration-opcode-compiler-test.js, packages/htmlbars-runtime/lib/expression-visitor.js, packages/htmlbars-runtime/lib/render.js, packages/htmlbars-util/lib/template-utils.js
=> Ensure statement nodes are the same length.
