packages/htmlbars-compiler/tests/html-compiler-test.js, packages/htmlbars-syntax/lib/tokenizer.js
Takes care of https://github.com/emberjs/ember.js/issues/10117 and another case where the error given wasn't ideal (it was treating the `/` as part of the attribute value and saying `Unquoted attribute value must be a single string or mustache`)
=> Improve HTML validation and error messages thrown

packages/morph/lib/dom-helper.js, packages/morph/tests/dom-helper-test.js
Previously, child nodes were being looked up directly via an element’s
`childNodes` array. However, @krisselden had some concerns around
performance and our future ability to do things like diffing if we have
to precisely simulate the behavior of `childNodes`.
This commit introduces a new `childAtIndex` abstraction that allows us
to create an alternate implementation that walks a linked list instead
of assuming an array implementation.
=> Introduce a childAtIndex abstraction

packages/htmlbars-compiler/lib/hydration-javascript-compiler.js, packages/htmlbars-compiler/tests/fragment-test.js, packages/htmlbars-test-helpers/lib/main.js, packages/morph/lib/dom-helper.js, packages/morph/tests/attr-morph-test.js
Fixes https://github.com/tildeio/htmlbars/issues/229.
-- Convert value for setAttribute() to string
-- Make repairClonedNode() safe to call on uncloned nodes (e.g. first rendering)
Tested with IE 11, and I expect based on what was failing before that it will also take care of IE 9 and 10, but let's see what the saucelabs tests say.  My first approach was to not call `repairClonedNode()` the first time (by modifying the code for `template.render()`), but it made a different test fail, and having the dom helper handle it seems more appropriate anyway.
The added tests were not strictly speaking required, since there were other failing tests, but these make the failure's cause explicit.
[EDIT: passes IE 8+]
=> Fix test failures on Internet Explorer (#229)

packages/htmlbars-compiler/tests/html-compiler-test.js, packages/morph/lib/dom-helper.js
This was the cause of https://github.com/emberjs/ember.js/issues/9948, and should take care of it.  The immediate problem was that the dom helper was left with the last namespace used in `build()` function.  But, more broadly, I think the appropriate namespace  for `parseHTML()` is that for the morph's contextual element (i.e. either its parent or the template's contextual element), rather than always the template's.  The two tests I added are really testing the same thing, but they cover what seem like important cases, so I figured I should include both.  
[Deleted: some mistaken tangential speculation... later findings instead:
With chrome, `parseHTML` works fine for svg stuff even if it goes down the `else` branch.  As a result, the second test I added was passing in chrome even before …
=> Use correct namespace in parseHTML() (ember #9948)

packages/htmlbars-compiler/lib/fragment-javascript-compiler.js, packages/htmlbars-compiler/tests/html-compiler-test.js
Demo showing the same is parsed as `disabled: true` in normal HTML: http://jsbin.com/magegorene/1/
paired with @rwjblue on this.
=> Fix <input disabled>

packages/morph/lib/dom-helper.js
We may want to handle `null` differently in the future as @mixonic has been considering, but for now this should eliminate the distracting failures in IE 10 and 11.  Not sure about IE 8, it probably has its own issues.
=> Call `String` on value in `setAttributeNS` (for IE 10-11)

packages/morph/lib/attr-morph.js, packages/morph/lib/dom-helper.js, packages/morph/lib/dom-helper/prop.js, packages/morph/tests/attr-morph-test.js, packages/morph/tests/dom-helper-test.js
Open for debate. Maybe this should be part of another layer in Ember. IMO it is ok here.
Ember expects setting an attribute binding to `undefined` or `NaN` to remove the attribute entirely. This follows that logic.
=> Change setProperty and morph to remove an undefined or NaN attr value

packages/morph/lib/dom-helper/build-html-dom.js, packages/morph/tests/dom-helper-test.js, packages/morph/tests/morph-test.js
I some cases (like select tests in Ember), numbers may be passed to `parseHTML`. This fixes that code path for IE <10.
=> Allow numbers to be parsed as HTML in IE

packages/htmlbars-compiler/lib/fragment-opcode-compiler.js, packages/htmlbars-compiler/lib/hydration-opcode-compiler.js, packages/htmlbars-compiler/lib/utils.js, packages/htmlbars-compiler/tests/html-compiler-test.js, packages/htmlbars-util/lib/main.js, packages/htmlbars-util/lib/namespaces.js, packages/morph/lib/attr-morph.js, packages/morph/tests/attr-morph-test.js
This will allow `bind-attr` to work with namespaced attributes (no further changes needed), as well as eventually attributes bound via ember views (so long as the full attribute name is passed to `createAttrMorph`).  Also added a test for the bound case, which wasn't covered.
=> Add namespace detection in `AttrMorph`

packages/htmlbars-compiler/tests/html-compiler-test.js, packages/htmlbars-syntax/lib/node-handlers.js
For https://github.com/tildeio/htmlbars/issues/254.
Includes tests for both the basic case and one with two unclosed elements.  The implementation will always throw on the last unclosed one left.  So the second test is currently testing an implementation detail.  I'd be open to removing it or modifying it to only check that some error is thrown but be agnostic as to which element it's about.
=> Include line number in error thrown for unclosed html element (#254)

packages/morph/lib/dom-helper.js, packages/morph/tests/dom-helper-test.js
Fixes #251
Old IE cannot remove svg attributes. Create a slow path for it.
=> removeAttribute fix for IE <11 and svg

.jshintrc, packages/morph/lib/dom-helper.js, packages/morph/tests/dom-helper-test.js
This implementation entirely removes the dependency on an element’s
`childNodes` live collection. This is beneficial because:
1. IE8 required a bounds check that relied on childNodes.length, which
in turn meant we had to implement an array-backed live collection of childNodes in simple-dom
which is slow and error-prone, and
3. The browser just uses a linked list anyway and we were forcing *it*
to materialize and keep updated a live collection until GC time.
This implementation just does what the browser would do anyway, while
making our simple-dom implementation actually, well, simple, and
includes notes about all of this for future fearless adventurers who
find themselves in this area of the code.
=> Use linked list walking for childAtIndex

packages/morph/lib/dom-helper.js, packages/morph/tests/dom-helper-test.js
In order to sanitize potentially dangerous URLs that contain executable
behavior (e.g. “javascript:” URLs), we need to determine the protocol.
Unfortunately, URL parsing is notoriously error-prone, so we want to use
the host environment’s native functionality such that the protocol we
report is the same as what it will act upon.
In this case, we expose a `protocolForURL` hook that uses a generated
`<a>` element to set its `href` and check the resulting `protocol`. A
Node.js implementation could fall back to using the `url` package that
is included in the standard library.
=> Add hook for extracting protocol from URLs

packages/morph-attr/lib/main.js, packages/morph-attr/lib/sanitize-attribute-value.js, packages/morph-attr/tests/attr-morph/sanitize-attribute-value-test.js
Update the logic to be more like Ember https://github.com/emberjs/ember.js/blob/04463cf3f65625fbbdc8b09efaf402a43dca4de0/packages/ember-views/lib/system/sanitize_attribute_value.js#L22 which means we should soon be able to drop the Ember version.
Also exposes the sanitize function on morph-attr main.
=> Pass dom helper to sanitizer

packages/dom-helper/lib/main.js, packages/htmlbars-compiler/lib/template-compiler.js, packages/htmlbars-compiler/tests/html-compiler-test.js
Will implement what's discussed in https://github.com/tildeio/htmlbars/pull/277.  However, I'm stuck without an IE8 VM at the moment, so am using saucelabs as my IE8 testing rig.  So I'm opening this PR before it's ready.  Will remove the WIP from the title and let you know when it's done.
=> Only use `cloneNode` when appropriate

packages/htmlbars-compiler/lib/main.js
I've tried including `htmlbars-compiler` into my project and discovered that `compilerSpec` is not defined. Instead, `htmlbars-compiler/compiler` exports a function named `compileSpec`, which `htmlbars-compiler` mistakingly imports and re-exports as `compilerSpec`. It seems this file is not used anywhere else neither within HTMLBars nor in Ember. That's the only occurrence of the string `compilerSpec` in the entire project.
=> compilerSpec -> compileSpec

packages/dom-helper/lib/main.js, packages/htmlbars-compiler/lib/hydration-javascript-compiler.js, packages/htmlbars-compiler/lib/hydration-opcode-compiler.js, packages/htmlbars-compiler/tests/html-compiler-test.js, packages/htmlbars-compiler/tests/hydration-opcode-compiler-test.js
Previously, if a template’s first (or last) child was a dynamic node
(like a mustache or block), the associated render node’s firstChild or
lastChild would change.
```hbs
{{#if condition}}{{value}}{{/if}}
```
In this case, the render node associated with the `#if` helper cannot
have stable `firstNode` and `lastNode`, because when the nodes
associated with `value` change, the nodes associated with the `if`
helper must change as well.
The solution was to require that templates create fragments with stable
start and end nodes. If the first node is dynamic, we insert a boundary
empty text node to ensure that the template’s boundaries will not
change.
Conflicts:
packages/htmlbars-compiler/lib/hydration-javascript-compiler.js
packages/htmlbars-compiler/tests/dirtying-test.js …
=> Ensure templates always have stable boundaries

package.json
Allows using `ember serve` to run tests.
=> Update ember-cli to 0.1.13.

Brocfile.js, package.json, packages/htmlbars-compiler/lib/template-compiler.js, packages/htmlbars-compiler/tests/template-compiler-test.js
It will use the current version (including SHA when not a tag) by default, but can be provided to the `compile` function.
The goal is to allow Ember to confirm that templates were compiled with the same compiler/revision as the running Ember version.
---
I'd like to pull this into 0.11 (Ember Canary) and 0.10 (Ember Beta) branches, to provide much better feedback when a mismatch has occurred.
=> Add revision to template output.

.travis.yml, README.md, bin/run-tests.js, package.json, testem-sauce.json, testem.json
After https://github.com/tildeio/htmlbars/pull/293, this should works now.
* Use ember-cli for testing
* Moved cross-browser testing options into a separate config
* Removed testem dependency
=> Use ember-cli for tests instead of testem directly

package.json
ember-cli-sauce stopped relying on a saucie fork.
All changes: https://github.com/johanneswuerbach/ember-cli-sauce/compare/v0.0.7...v0.1.0
=> Updated ember-cli-sauce

packages/htmlbars-compiler/lib/compiler.js
The `compileSpec` and `template` functions are defined two times in the same file.
=> Removes duplicate code

README.md
should be "/tests/" (with the trailing slash)
=> [DOC] Fix the URL for running tests in a browser

.jshintrc, packages/dom-helper/lib/main.js, packages/dom-helper/tests/dom-helper-test.js
IE dislikes setting null or undefined values to value and type properties. Several browsers only accept a blank string as an appropriate value for "no url" with src tags.
This brings over logic previously living in Ember.
=> Normalize values passed to setPropertyStrict

packages/htmlbars-syntax/lib/parser.js
This allows AST plugins to have more information about the thing being compiled. The intent is for this to be a way to provide compile time template deprecations and still be able to indicate the module path for the template being compiled.
The general idea is that ember-cli-htmlbars will call `precompile` something like:
```javascript
var compiler = require('./bower_components/ember/ember-template-compiler');
var template = compiler.precompile(input, {
moduleName: 'some-app/path/to-template/stuff'
});
```
And then Ember can have an AST preprocessor that deprecates things (like `{{bind-attr}}`) at compile time, but still provides the template path being compiled. Without the module name tracking down deprecations on compile is extremely difficult.
=> Pass options through to AST plugins.

demos/compile-and-run.html
I was running `compile-and-run.html` through htmlbars (don't ask :stuck_out_tongue:), and it blew up because `</input>` is invalid HTML
=> In HTML, <input> is a void element

packages/htmlbars-runtime/lib/expression-visitor.js, packages/htmlbars-runtime/lib/hooks.js, packages/htmlbars-runtime/lib/morph.js
This let's a node's childEnv persist correctly when the node itself was
not dirty. It fixes and simplifies the way outlets inherit their state
in Glimmer.
=> Stable childEnv

packages/htmlbars-runtime/lib/hooks.js
Export handleRedirect and handleKeyword from runtime.
This allows easier customization of hooks when handleRedirect and/or handleKeyword are needed.
The specific use-case/need is for a custom `element` hook in Ember, so that we can also add a deprecation when the helper returns a value to be added to an element (like `<div {{bind-attr id=foo}}></div>`).
=> Allow `element` hook to be customized.

packages/htmlbars-compiler/lib/hydration-opcode-compiler.js, packages/htmlbars-runtime/lib/expression-visitor.js, packages/htmlbars-syntax/lib/builders.js, packages/htmlbars-syntax/lib/node-handlers.js, packages/htmlbars-syntax/tests/parser-node-test.js
The recent update to Handlebars 3.0.2 added `NullLiteral` to the list of known nodes.  This PR allows HTMLBars to handle this properly.
This fixes a few tests that the Handlebars update caused to fail in Ember.
=> Add NullLiteral to HTMLBars.

packages/morph-attr/lib/main.js
Allows preserving cursor position, during a re-render when a user is entering text into a bound input.
=> Do not set `.value` property to the current value.

packages/morph-attr/lib/main.js, packages/morph-attr/tests/attr-morph-test.js
These methods are called by `renderAndCleanup` (from `template-utils`)
when an AttrMorph is created in a block helpers template:
```javascript
{{input type="checkbox" checked=checked}}
{{#if checked}}
<a href={{"http://google.com"}}>google.com</a>
{{else}}
<a href={{"http://yahoo.com"}}>yahoo.com</a>
{{/if}}
```
In the above example, when `checked` is toggled the `href` AttrMorphs get `.clear()`
and `.destroy()` called on them.
=> Add AttrMorph.prototype.clear and AttrMorph.prototype.destroy.

packages/htmlbars-compiler/tests/html-compiler-test.js, packages/htmlbars-syntax/lib/token-handlers.js
While looking at #323, I also noticed that the error message was "wrong" (inaccurate), so I fixed it and added a test case for it. Previously, the "void elements cannot have end tags" only work if this happens in the root context.
This is the minimal diff to pass the test. Open to suggestions to make it more elegant.
Input:
```html
<div>
<input></input>
</div>
```
Before:
```
Closing tag `input` (on line 2) did not match last open tag `div` (on line 1).
```
After:
```
Invalid end tag `input` (on line 2) (void elements cannot have end tags).
```
=> Fix error for void elements

packages/dom-helper/lib/main.js, packages/dom-helper/tests/dom-helper-test.js, packages/dom-helper/tests/element-morph-test.js
Addresses https://github.com/emberjs/ember.js/issues/11032.
=> Add ElementMorph.prototype.clear and ElementMorph.prototype.destroy.

LIFECYCLE.md, packages/htmlbars-runtime/lib/hooks.js
The documentation uses `createShadowScope` but both htmlbars and ember use `bindShadowScope` as the actual name.
I don't know enough (yet) to know which is "more correct" but since actual code is the the former, PR'ing to make consistent.
=> Fix incorrect documentated name createShadowScope -> bindShadowScope

packages/htmlbars-compiler/lib/template-compiler.js, packages/htmlbars-compiler/tests/compile-tests.js, packages/htmlbars-compiler/tests/template-compiler-test.js, packages/htmlbars-runtime/lib/hooks.js, packages/htmlbars-runtime/lib/render.js
Adds `buildMeta` callback to `compile` options.
If a `buildMeta` function is present in the options passed to `compile` or
`compileSpec`, the return value will be used for the `meta` key in the template
output.
This allows the host frameworks compiler to add metadata details (moduleName,
revision, etc) as needed.
```javascript
var template = compile('Hi, {{name}}!', {
buildMeta: function(program) {
return {
isHTMLBars: true,
revision: 'WAT@LOL.1234',
loc: program.loc
};
}
});
template.meta.revision; // => 'WAT@LOL.1234'
```
---
Sample template output (no buildMeta callback):
```javascript
(function() {
return {
meta: {},
arity: 0,
cachedFragment: null,
hasRendered: false,
buildFragment: function buildFragment(dom) {
var el0 = dom.createDocumentFragment();
var el1 = …
```
=> Add `meta` to template output.

packages/htmlbars-runtime/lib/expression-visitor.js, packages/htmlbars-runtime/lib/hooks.js, packages/htmlbars-util/lib/template-utils.js
This exposes the inverse template to the component hook, and parameterized `bindBlock` and `yield` so they can optionally use other block names (which will presumably just be "inverse" for now).
=> Expose inverse block to component hook

packages/htmlbars-runtime/lib/render.js, packages/htmlbars-runtime/tests/main-test.js, packages/htmlbars-syntax/lib/token-handlers.js, packages/htmlbars-util/lib/void-tag-names.js
Prior to this change calling `manualElement('input', {})` would result in the following DOM:
```html
<input></input>
```
This is incorrect because `input` is a void element.
---
Addresses https://github.com/emberjs/ember.js/issues/11157.
=> Prevent void elements from always including a comment node.

packages/htmlbars-runtime/lib/hooks.js
`null` paths were being passed to the `classify` and `handleKeyword` hook. This was obviously not intended, and the fact that code in `classify` and `handleKeyword` is safe for a `null` path was not intentional.
This fixes https://github.com/emberjs/ember.js/pull/11223 in Ember.
=> Do not attempt to redirect null paths

packages/dom-helper/lib/prop.js, packages/dom-helper/tests/dom-helper-test.js, packages/dom-helper/tests/prop-test.js
fixes emberjs/ember.js#11112 and sets the stage for #353 which is the same code-path and desired outcome but different cause.
=> [BUGFIX] Adds the ability to blacklist props that should use setAttribute because of browser compliance issues

packages/htmlbars-runtime/lib/hooks.js
If `invokeHelper` is to return a stream, we must ensure that stream always has a value generated. Sometimes a stream's compute function may yield a block instead of generate a value.
This forces compute to happen once.
There is probably a better way to achieve the base goal here. For example, I should likely only link nodes that a new-style `Ember.Helper`, where they cannot interact with `yield` etc.
See also: https://github.com/mixonic/ember.js/pull/8
=> Helper streams require get

packages/htmlbars-runtime/lib/expression-visitor.js
`morph.linkedResults` must be linked for helpers to rerender upon invalidation.
=> link to content results (ember helpers)

packages/htmlbars-runtime/lib/hooks.js
linking for an inline value must occur before the value is called if you want deactivation
=> Change inline linking

packages/htmlbars-syntax/lib/main.js, packages/htmlbars-syntax/lib/traversal/traverse.js, packages/htmlbars-syntax/lib/types/visitor-keys.js, packages/htmlbars-syntax/tests/traversal/visiting-node-test.js
Implements a new visitor that fully traverses the AST. It was designed in the spirit of Babel's transform. Usage:
```js
import { traverse } from "htmlbars-syntax";
let ast = parse(`{{name-tag name=(upcase user.name)}}`);
traverse(ast, {
PathExpression(node) {
console.log(node.original); // Logs "name-tag", "upcase", "user.name"
}
});
```
Alternatively, you can use the enter/exit format to capture when the node is entered and exited:
```js
import { traverse } from "htmlbars-syntax";
let ast = parse(`...`);
let depth = -1;
traverse(ast, {
Program: {
enter() { depth++; },
exit() { depth--; }
}
});
```
=> Implement new visitor

packages/htmlbars-syntax/lib/builders.js, packages/htmlbars-syntax/lib/traversal/errors.js, packages/htmlbars-syntax/lib/traversal/traverse.js, packages/htmlbars-syntax/tests/parser-node-test.js, packages/htmlbars-syntax/tests/support.js, packages/htmlbars-syntax/tests/traversal/manipulating-node-test.js, packages/htmlbars-syntax/tests/traversal/visiting-node-test.js
You can now return `null`, a node or an array of nodes inside of the `enter` and `exit` events to replace the current node. Returning `null` is equivalent to returning an empty array. You can only replace a node with multiple nodes (or zero nodes) if it is part of an array.
If you return a replacement in the `enter` event then replacement's child nodes **will not** be visited (the user created the nodes, so there's no point) and moreover the `exit` event for the current node **will not** be called (this would just be confusing, since the node has been replaced possibly by multiple nodes).
Here is an illustrative example from the tests:
```js
QUnit.test('Inside of a block', () => {
let ast = parse(`{{y}}{{#w}}{{x}}{{y}}{{z}}{{/w}}`);
traverse(ast, {
MustacheStatement(node) {
if …
```
=> Implement replacement API

packages/htmlbars-syntax/lib/traversal/errors.js, packages/htmlbars-syntax/lib/traversal/traverse.js, packages/htmlbars-syntax/tests/traversal/visiting-keys-node-test.js, packages/htmlbars-syntax/tests/traversal/visiting-node-test.js
You can now hook onto enter/exit events of individual visitor keys:
```js
traverse(ast, {
MustacheStatement: {
enter(node) { ... },
exit(node) { ... },
keys: {
params: {
enter(node, key) { ... },
exit(node, key) { ... },
},
hash(node, key) { ... }
}
}
```
The arguments `node`, `key` correspond to the current node and the current key being accessed on that node. The value is `node[key]`. In the example above, `node` is a `MustacheStatement` and `key` is `"params"` or `"hash"`. Typically you won't need to use the `key` argument unless you are sharing event handlers.
=> Extend the visitor API to support keys

packages/dom-helper/lib/main.js
TL;DR childNodes.item(index) sometimes fails, but childNodes[index] works.
The existence of this PR makes me sad.
=> [Bugfix] work around PhantomJS 2.0 quirk.

packages/htmlbars-syntax/lib/generation/print.js, packages/htmlbars-syntax/lib/main.js, packages/htmlbars-syntax/tests/generation/print-test.js
This is the most basic AST printer. It does **not** reproduce the exact source that generated the AST.
That is to say, these tests don't always pass:
`equal(print(parse(template)), template)`
`deepEqual(parse(print(ast)), ast)`
Currently, all statements and expressions are handled with the exception of comments, so the new source will have the same semantic meaning. However, certain formatting is lost.
Formatting:
Statements:
=> Implement AST printer

packages/htmlbars-compiler/tests/diffing-test.js, packages/htmlbars-runtime/lib/hooks.js
We are using `renderState.handledMorphs` as a way to know if a given key is duplicated or not (if it is duplicated we use a binning strategy to prevent errors), but we were setting `handleMorphs[key]` to `null` when the given morph was the last item in the list.
The fix is to keep `renderAndCleanup` and `yieldItem` using the same mechanism to know of the handled morphs (both should check via `key in handledMorphs`).
This is the fix for https://github.com/emberjs/ember.js/pull/11949.
=> Fix issue with duplicate keys and last item.

packages/htmlbars-runtime/lib/expression-visitor.js, packages/htmlbars-runtime/lib/main.js, packages/htmlbars-runtime/lib/node-visitor.js, packages/htmlbars-runtime/lib/render.js, packages/htmlbars-runtime/tests/main-test.js
While working on this, I realized that the AlwaysDirtyVisitor doesn't recurse into children nodes. Surely this is a bug. I am noting it here for posterity.
=> [REFACTOR] Split up visitor into expression and node parts

packages/htmlbars-compiler/tests/dirtying-test.js, packages/htmlbars-util/lib/morph-utils.js
`visitChildren` is used internally to visit all `Morph`'s and call a callback on each one found.  The most common usage of `visitChildren` in HTMLBars itself is for clearing morphs before rendering a new template.
Prior to this change, if we encounter a node with `morphList` we:
* add the `morphList` to the list of nodes to traverse
* call the provided callback
* traverse the `MorphList` and add all morphs found there to the list of
morphs to call the callback on
In general that is fine, except when the callback itself (in step 2 above) is mutating the `morph` and preventing the `MorphList` from being traversed. This is the case when changing an `{{if}}` with a `{{each}}` from the template to the inverse block, in that case the callback is calling `MorphList#clear()` which nullifies the …
=> Properly visit MorphLists in visitChildren.

packages/dom-helper/lib/prop.js, packages/dom-helper/tests/prop-test.js
fixes emberjs/ember.js#11869, Cc/ @stefanpenner
=> [BUGFIX] add `autocorrect` attr override because Mobile Safari hates us

packages/htmlbars-syntax/tests/parser-node-test.js
Adding `{{!~}}` to the end of a line in a htmlbars template file allows suppressing whitespace between that comment and the first non-whitespace character on the next line.
In my case this is useful when converting templates created in emblem (which by default suppresses whitespace) to htmlbars, without needing to manually squish all the dom tags together.
This behavior wasn't documented or tested anywhere.  Hence this PR.
related: https://github.com/tildeio/htmlbars/issues/305
=> test to show that stripping whitespace after comments is possible

packages/htmlbars-runtime/lib/main.js
I was trying to require the htmlbars-runtime package as a CommonJS module, but I kept receiving dependency errors.
On closer inspection, it looks like the import paths in `packages/htmlbars-runtime/lib/main.js` were inconsistent.
This PR should fix the module for use in CommonJS projects – I've tested the build and all seems fine, but let me know if there are any problems.
=> Fix htmlbars-runtime import paths

packages/htmlbars-util/lib/template-utils.js
We were already using an `undefined` check to determine if a match was found (as opposed to `x in morphMap`), so the `delete` is not actually needed.
=> Avoid deleting items from `morphMap`.

packages/dom-helper/lib/main.js
The current implementation of the DOM helper’s `protocolForURL` relies
on the implicit parsing and normalization that the browser’s DOM does
when setting the A element’s `href` property.
However, the DOM helper is often used with subset DOM implementations
like simple-dom. In those cases, we cannot rely on this normalization.
This commit detects when the DOM Helper is running in Node and uses
the built-in URL package to parse the protocol instead.
/cc @wycats @chancancode @rwjblue @stefanpenner
=> Adds Node-compatible protocolForURL

packages/dom-helper/lib/main.js
This is for fastboot sandboxing.  URL is provided as a global to the
sandbox, and we'll use that rather than trying to require('url').
=> Use the global URL in node context if in sandbox

packages/htmlbars-syntax/lib/parser/tokenizer-event-handlers.js, packages/htmlbars-syntax/tests/parser-node-test.js
HTMLBars need to be able to generate components with syntax `my.comp` for
implementing contexual components.
emberjs/ember.js#12617
=> [FEATURE] Add contextual component syntax

packages/htmlbars-runtime/lib/hooks.js, packages/htmlbars-runtime/tests/hooks-test.js
When an `range` calls `handleRedirect` it sets the `params` to an array
containing its value. This causes problems with contextual components called
with dot syntax.
If a contextual component is called with dot syntax and any kind of arguments
(either `params` and `attrs`) it gets compiled to `inline`. But when called
without any of them (`{{contextual.my-component}}`), it gets compiled to
a `range`.
The `range` calls to `handleRedirect` but sets `params` to be `[value]` instead
of an empty array, causing `positionalParams` to receive the wrong value.
Fixes emberjs/ember.js#12717
=> [BUGFIX beta] Range redirection

packages/htmlbars-compiler/tests/html-compiler-test.js, packages/htmlbars-syntax/lib/parser/tokenizer-event-handlers.js, packages/htmlbars-syntax/tests/parser-node-test.js
As specified in emberjs/ember.js#12769,
```handlebars
<input type="text" value={{favoriteBand}} onblur={{action "bandDidChange"}}/>
```
is valid HTML but HTMLbars was raising the following exception:
An unquoted attribute value must be a string or a mustache, preceeded by
whitespace or a '=' character, and followed by whitespace or a '>'
character (on line X)
This commit addresses the problem and rephrases the assertion message.
=> [BUGFIX beta] Allow unquoted attributes before the end of a self-closing tag

packages/morph-attr/lib/main.js, packages/morph-attr/tests/attr-morph-test.js
People are using bound `<input>`s. For the most part everything works great.
```hbs
<input type="checkbox"
checked={{user.isCool}}
oninput={{action 'saveCoolness' user}} >
<textarea value={{user.description}}
oninput={{action 'saveDescription' user}} >
```
```js
actions: {
saveCoolness(user, event) {
user.set('isCool', event.target.checked);
Ember.run.throttle(user, 'save', 500);
},
saveDescription(user, event) {
user.set('description', event.target.value);
Ember.run.throttle(user, 'save', 500);
}
}
```
But not everything is rainbows and butterflies. Text inputs have an annoying
wart. Whenever you update their `value`, the cursor is moved to the end of the
input. This becomes a problem when you are trying to edit text in the middle of
a text input. Curiously, this issue doesn't affect …
=> [BUGFIX] Fix text input cursor behavior

packages/htmlbars-syntax/lib/parser/handlebars-node-visitors.js, packages/htmlbars-syntax/tests/loc-node-test.js
Given the following:
```hbs
<div>
{{#if isSingleError}}
Single error here!
{{else if errors}}
Multiple errors here!
{{else}}
No errors found!
{{/if}}
</div>
```
The `ElementNode` for the `<div>` was indicating that its `loc.end.column` was 12. This is ultimately due to how Handlebars handles trailing newlines after the `{{/if}}`. We were properly detecting that the node was `rightStripped` and adding the number of stripped newlines to the `tokenizer.line` number, but we did not reset the `tokenizer.column` also.
The fix is to ensure that the column is reset when incrementing the line count.
---
This is also being fixed in Glimmer in https://github.com/tildeio/glimmer/pull/91
=> Fix loc info for content statements with leading newlines.

packages/htmlbars-syntax/lib/parser/handlebars-node-visitors.js, packages/htmlbars-syntax/tests/loc-node-test.js
https://github.com/tildeio/htmlbars/pull/450 initially intended to fix this, but while adding more examples to the test scenarios I zeroed in on another bug (that was ultimately wider spread than this one).
When a closing block tag is followed by a newline, that newline is stripped. We were properly handling the line being stripped, but not resetting the column when we incremented the line.
This ensures that the column is reset to 0 if the lines are incremented.
=> Ensure column is reset when incrementing right stripped lines.

packages/dom-helper/lib/main.js
The node version of protocolForURL was throwing an exception if the url is undefined [here](https://github.com/tildeio/htmlbars/blob/master/packages/dom-helper/lib/main.js#L619).  This is invoked in [sanitizeAttributeValue](https://github.com/tildeio/htmlbars/blob/master/packages/morph-attr/lib/sanitize-attribute-value.js#L47).  This was calling issues for bound attributes with no value in FastBoot environments.
This PR returns a sensible default (`:`) from `nodeProtocolForURL` when the `url` argument is a non-string.
I'm not sure how to test this though.  I'd like to get a test in place if possible before merging.
/cc @tomdale
=> Handle null/undefined url in nodeProtocolForURL

bower.json, packages/htmlbars-syntax/lib/parser/tokenizer-event-handlers.js, packages/htmlbars-syntax/tests/loc-node-test.js
The EventedTokenizer only invokes the `beginComment` and `beginAttribute` methods **after** it has consumed the identifying chars.
Fixes https://github.com/rwjblue/ember-cli-template-lint/issues/89.
=> Fix comment and attribute start column.

packages/htmlbars-syntax/lib/parser/handlebars-node-visitors.js, packages/htmlbars-syntax/tests/loc-node-test.js
Previously, we were only handling the Handlebars default "eating" of a newline after a block statement but did not properly handle `~}}` at the end of a block statement.
This updates to also calculate the column offsets (and adds tests).
Given the following:
```hbs
{{#if foo~}}
<div></div>
{{/if}}
```
Before these changes, the `<div>` would have a starting column of `0`.
After these changes, the `<div>` has the correct starting column of `2`.
---
Related to https://github.com/rwjblue/ember-template-lint/issues/34.
=> Properly handle trailing whitespace controls.

bower.json, packages/htmlbars-syntax/tests/loc-node-test.js
This requires https://github.com/tildeio/simple-html-tokenizer/pull/31 (published in simple-html-tokenizer@0.2.4) to pass.
=> Add tests for unquoted attribute location info.

bower.json, packages/htmlbars-syntax/lib/parser/tokenizer-event-handlers.js, packages/htmlbars-syntax/tests/loc-node-test.js
* Rely on simple-html-tokenizer calling `beginAttribute` correctly. Relies on changes in SHT to call `beginAttribute` with the proper `column` and `line` information.
* Use `tagOpen` hook to handle tag start loc tracking.
* Removes usage of `tagLine` and `tagColumn`.
* Track AttrNode value location information.
=> Handle loc tracking locally.
